### PR TITLE
Voila as an ExtensionApp (was #270)

### PR DESCRIPTION
**Pull request by davidbrochart**
Yet another shot at #270.
@Zsailer is mostly the author.

### CODE REVIEW

**Comment by vidartf** [comment]
> @Zsailer is mostly the author.

The git history does not reflect this though :-/

**Comment by davidbrochart** [comment]
I know, but master has diverged too much. I found it easier to try and report the changes @Zsailer had done in his PR, to today's master.

**Comment by Zsailer** [comment]
Thanks, @vidartf. I'm really not worried about the credit. I appreciate the shout-out! 😄 

In the meantime, Jupyter Server's extension API has diverged a bit since I made the original PR as well. I'm happy to jump on this PR with you @davidbrochart. I was planning to work on this extension as soon as released Jupyter Server 1.0 this week.

**Comment by maartenbreddels** [comment]
This is actually #492 a continuation of right?

**Comment by davidbrochart** [comment]
Yes, but I'm working on yet another one!

**Comment by davidbrochart** [comment]
Closing in favor of https://github.com/voila-dashboards/voila/pull/592.

**Pull request closed without merging**
