### PR TITLE
Extendable voila

### PR DESCRIPTION
**Pull request by martinRenou**
## References

This is the part of https://github.com/voila-dashboards/voila/pull/1187 (PR that was later reverted), that applies to Voila only. The rest of the PR (introduction to Voilite/Voici) is now in a separate repository: https://github.com/voila-dashboards/voici

### CODE REVIEW

**Comment by trungleduc** [comment]
update galata references

**Comment by martinRenou** [comment]
Not sure the references should be updated, the failure seems legit: all outputs are duplicated.

**Comment by trungleduc** [comment]
> Not sure the references should be updated, the failure seems legit: all outputs are duplicated.

And the bot is also broken

**Comment by martinRenou** [comment]
> And the bot is also broken

Indeed, it looks like a NodeJS version issue

**Comment by martinRenou** [comment]
@trungleduc UI-tests are green now!

**Comment by trungleduc** [comment]
Thanks @martinRenou

**Pull request merged**
