### PR TITLE
Pass Papermill parameters from request through to notebook

### PR DESCRIPTION
**Pull request by timkpaine**
This PR does the following:
- tries to get the `parameters` argument from either the query parameter or body of the request
- if `parameters` is passed and it is a dict, it calls `papermill.parameterize.parameterize_notebook` on the underlying notebook, prior to execution

### CODE REVIEW

**Comment by timkpaine** [comment]
tmp

**Comment by timkpaine** [comment]
@vidartf can we inspect notebooks for their parameters and make a UI for injecting them prior to launch in `phoila`

**Comment by timkpaine** [comment]
@SylvainCorlay @maartenbreddels @jtpio thoughts on this? it seems like a natural thing to do, though the implementation could be different

**Comment by jtpio** [comment]
Thanks @timkpaine.

That sounds like a natural thing to do indeed, and would definitely be useful.

The main question is probably whether we want voila to depend on papermill. There was some similar discussion in JupyterLab about this (papermill vs notebook standard): https://github.com/jupyterlab/jupyterlab/pull/8410

**Comment by timkpaine** [comment]
@jtpio prelaunch hook + example showing how to use papermill would accomplish the same functionality without the dependency

**Comment by timkpaine** [comment]
closed by https://github.com/voila-dashboards/voila/pull/724

**Pull request closed without merging**
