### PR TITLE
Don't return resources

### PR DESCRIPTION
**Pull request by davidbrochart**
This led to the following error when a cell was erroring out:
```
jinja2.exceptions.UndefinedError: 'tuple object' has no attribute 'get'
```

### CODE REVIEW

**Comment by maartenbreddels** [comment]
I'd like to have a test for this, do you feel like doing that?

**Comment by davidbrochart** [comment]
It's tricky because a test with e.g. a syntax error in a cell doesn't fail, and doesn't show the error in `stdout` or `stderr` as if Voila were run on the CLI.

**Comment by maartenbreddels** [comment]
It should give this error msg in red right? `Run with --debug` .... I think that feature isn't really tested at all.

**Comment by davidbrochart** [comment]
We want to test the presence of `'tuple object' has no attribute 'get', but it's not there with pytest.

**Comment by maartenbreddels** [comment]
I think we don't have to test that detailed. By default, voila should render a clean error message, now it does not do that. So I think if we just add a new test notebook, with say an import error, or syntax error, we can test if the rendered HTML contains that nice error message. What do you think about that?

**Comment by davidbrochart** [comment]
Sounds good, I added a test for that and checked that it was failing before this PR.

**Pull request merged**
