### PR TITLE
Troubleshoot the check release workflow

### PR DESCRIPTION
**Pull request by jtpio**
## References

Another attempt at troubleshooting the CI.

Similar to https://github.com/voila-dashboards/voila/pull/1207

### CODE REVIEW

**Comment by jtpio** [comment]
cc @martinRenou the check release check seems to be passing now with this change.

Suspecting this is related to the bump to node 16 in https://github.com/jupyterlab/maintainer-tools/pull/121.

**Comment by jtpio** [comment]
This might be related to a new behavior in npm executing the `prepare` script by default.

**Comment by martinRenou** [comment]
Good catch on this! Thanks @jtpio !

meeseeksdev please backport to 0.3.x

**Comment by martinRenou** [comment]
There seems to be an issue with the ui-tests, I'm currently trying to understand the issue.

**Comment by jtpio** [comment]
> There seems to be an issue with the ui-tests, I'm currently trying to understand the issue.

Alright, this could probably be addressed separately? (for example in https://github.com/voila-dashboards/voila/pull/1205?).

**Comment by martinRenou** [comment]
> Alright, this could probably be addressed separately? 

Sure!

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
