### PR TITLE
Fix wrong base_url

### LINKED ISSUE #992: Handling of the `base_url` in `0.3.0a0`
## Description

Testing `0.3.0a0` on Binder gives the following:

image

Here we see that we are trying the fetch `require.min.js` without taking into account the base url.

## Reproduce

- Voila 0.3.0a0: https://gist.github.com/jtpio/7bc4de695b1b37e6cb6ae6968fd2c426
- Voila 0.2.16: https://gist.github.com/jtpio/58cda617f58043953357fbbb01e48936

## Context

This works fine with `0.2.16` on Binder, so probably an issue introduced in #936 (cc @trungleduc)

- voila version: `0.3.0a0`
- Operating System and version: Ubuntu 20.04
- Browser and version: Chromium / Firefox

### PR DESCRIPTION
**Pull request by trungleduc**
Close #992

### CODE REVIEW

**Comment by trungleduc** [comment]
@jtpio can we re-release `0.3.0a0` with this pass?

**Comment by jtpio** [comment]
> @jtpio can we re-release `0.3.0a0` with this pass?

We can release `0.3.0a1` it's fine :+1:

**Comment by jtpio** [comment]
Looks like there is an ongoing issue with GitHub Actions at the moment (checks are not triggered):

image

**Comment by trungleduc** [comment]
It works now on Binder 

https://user-images.githubusercontent.com/4451292/136060241-03cefd1b-ec86-4546-bc45-48ffc99ae2c8.mp4

**Comment by jtpio** [comment]
Nice.

I was wondering why we didn't have the Binder link posted on new PRs anymore, but that is because the benchmark workflow overwrites it:

image

**Comment by jtpio** [comment]
> I was wondering why we didn't have the Binder link posted on new PRs anymore, but that is because the benchmark workflow overwrites it:



> I was wondering why we didn't have the Binder link posted on new PRs anymore, but that is because the benchmark workflow overwrites it:

Tracked in https://github.com/voila-dashboards/voila/issues/994

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
> Looks like there is an ongoing issue with GitHub Actions at the moment (checks are not triggered):

Let's wait a bit before making the release as there still seems to be issues on GitHub side.

**Comment by trungleduc** [comment]
@jtpio it looks like GHA returned to normal now, we can cut a new alpha ?

**Pull request merged**
