### PR TITLE
fix: support DeferredConfigString (hack)

### PR DESCRIPTION
**Pull request by maartenbreddels**
This is the best backward compatible fix I can think of, but I did not confirm yet it works.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
TBH, why are we using `self.voila_configuration.config.VoilaConfiguration.resources` instead of just `self.voila_configuration.resources`?

**Comment by SylvainCorlay** [comment]
@jtpio @maartenbreddels should this be enough to work with the classic notebook server? Ready to go?

**Comment by jtpio** [comment]
Just tried this fix together with https://github.com/voila-dashboards/voila/pull/709, and it seems to work with the classic notebook server :+1:

**Comment by maartenbreddels** [comment]
The travis failure is strange, but cannot be related to this. I'm ok-ish to merge this.

**Comment by SylvainCorlay** [comment]
Merged. When all is green, I will tag 0.2.2.

**Pull request merged**
