### PR TITLE
UI-tests: Update ipympl screenshots

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
Triggering CI

**Review by trungleduc — APPROVED** [review]

**Comment by trungleduc** [comment]
Thanks @martinRenou !

**Comment by martinRenou** [comment]
For some reason the Windows test is failing, but I guess it's unrelated?

**Comment by trungleduc** [comment]
Yes, it's unrelated, I'm fighting with these flaky tests for a long time but no result.

**Comment by martinRenou** [comment]
Thanks!

**Pull request merged**
