### PR TITLE
Clean templates

### PR DESCRIPTION
**Pull request by martinRenou**
There was a lot of unwanted noise in those templates like the "login widget". I suppose it was due to a copy/paste from JupyterLab/Notebook templates.

I also improved the code indentation.

### CODE REVIEW

**Comment by martinRenou** [comment]
Putting this in WIP, we need to check if this login_widget is for the authentication when the token is not in the url

**Comment by jtpio** [comment]
> Putting this in WIP, we need to check if this login_widget is for the authentication when the token is not in the url

:+1: 

This `login_widget` was also indirectly mentioned in https://github.com/voila-dashboards/voila/issues/260 I believe.

**Comment by martinRenou** [comment]
It seems to me that those login/logout widgets are leftovers...

When you browse Voila without the token you get redirected to `http://localhost:8888/login?next=%2Fvoila`, so it is not handled by Voila.

And the issue you pointed to @jtpio is comforting me in thinking those widgets are useless.

**Comment by maartenbreddels** [comment]
What is page.html actually? Is that the classic notebook template? If so, we can remove it I guess.

**Comment by jtpio** [comment]
> It seems to me that those login/logout widgets are leftovers...

That was my impression too.

**Comment by martinRenou** [comment]
So, are you ok with this @maartenbreddels ?

**Comment by maartenbreddels** [comment]
Yeah, I'm a bit unsure about the login/logout stuff. I'm not so familiar with it, don't know if it functions at all, and I wonder if people already depend on it.

@timkpaine : you might be using the login/logout features, is it functional at all?

If it does not function, I'm ok with this PR.

**Comment by martinRenou** [comment]
@maartenbreddels you added this `login_widget` part. https://github.com/voila-dashboards/voila/commit/28faacc9b03b160fd8fa920ad045f4ec0667ab67. Was it some copy-paste from somewhere else?

**Pull request merged**
