### PR TITLE
Show the list of voila kernels in the running tabs

### PR DESCRIPTION
**Pull request by jtpio**
**EDIT**: this branch depends on https://github.com/voila-dashboards/voila/pull/41. The relevant changes for this current PR are the ones under `packages/jupyterlab-voila/*`. 

### Motivation

Having such list can be useful to get an idea of the number of kernels that are currently running.

It should also help troubleshoot issues such as https://github.com/voila-dashboards/voila/issues/479, https://github.com/voila-dashboards/voila/issues/528, https://github.com/voila-dashboards/voila/issues/562.

### TODO

- [x] Add a new section to the running tabs
- [x] Filter the list of kernels to only show the ones started by Voila (for now it lists all the kernels)

preview-list-kernels

### CODE REVIEW

**Comment by jtpio** [comment]
Just rebased this PR onto https://github.com/voila-dashboards/voila/pull/41 so it can use the `GET /voila/api/kernels` endpoint to list the voila kernels kernels only.

**Comment by jtpio** [comment]
The relevant change for this PR is in https://github.com/voila-dashboards/voila/pull/611/commits/568d7a0c9b33115fd4a349248e0247296c72aa43 (might be updated on subsequent rebases)

**Comment by jtpio** [comment]
This might actually be fixed in JupyterLab directly: https://github.com/jupyterlab/jupyterlab/pull/13792.

**Comment by afshin** [comment]
> This might actually be fixed in JupyterLab directly: [jupyterlab/jupyterlab#13792](https://github.com/jupyterlab/jupyterlab/pull/13792).

As long as `api/kernels` returns the kernels in question, then yes!

**Comment by jtpio** [comment]
Just checked with `jupyterlab==4.0.0a35` and `voila==0.5.0a2` and the kernels appear to be listed in the running panel:

image

Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/13792, thanks @afshin!

**Pull request closed without merging**
