### PR TITLE
Update nbclient

### PR DESCRIPTION
**Pull request by martinRenou**
cc. @bnavigator

### CODE REVIEW

**Comment by jtpio** [comment]
Nice thanks!

**Review by jtpio — APPROVED** [review]
Diff looks good, waiting for the CI checks to complete.

Thanks!

**Comment by jtpio** [comment]
ah the CI checks are still running, maybe there is some real issue underneath (timeout).

**Comment by jtpio** [comment]
Cancelling and restarting the checks.

**Comment by jtpio** [comment]
Doing one more full CI kick.

**Comment by jtpio** [comment]
cc @davidbrochart who might know if something needs to be updated to handle the latest `nbclient`.

**Comment by bnavigator** [comment]
So, I tried 0.4.0rc0 on the openSUSE Build Service with the same change as here and first thought I could not reproduce the hang form GitHub Actions, But then noticed that the pytest started to hang before the first test as soon as I had updated jupyter-client from 7.3.4 to 7.4.2. I suspect a non-returning test fixture.

**Comment by bnavigator** [comment]
Pinning jupyter-client got rid of the hangs: https://github.com/bnavigator/voila/actions/runs/3268022596

That's not a viable solution but might lead us into the right direction.

Ping @blink1073

**Comment by blink1073** [comment]
Note there is a significant refactor in the the forthcoming `jupyter_client 8.0` to remove `nest-asyncio` and use public `asyncio` APIs.

**Comment by trungleduc** [comment]
Thanks @bnavigator  for the pointer, indeed the changes of `jupyter-client` from `7.4.1` to `7.4.2` (https://github.com/trungleduc/voila/pull/6) cause the hanging tests. But strangely i can't reproduce the issue while running the GHA locally with https://github.com/nektos/act.

The diff between the two version is very short (https://github.com/jupyter/jupyter_client/pull/852/files) but i can not find any clue from the diff. Ping @davidbrochart who might understand what happened here.

**Comment by davidbrochart** [comment]
I don't know, I see that @blink1073 backported a [fix from the PR that removes nest-asyncio](https://github.com/jupyter/jupyter_client/pull/852/commits/6607d5219f99b7e9c743186a79eb071b9ee9eb76), that might have consequences.

**Comment by blink1073** [comment]
Based on the diff, I would suspect the handling of [asyncio sockets](https://github.com/jupyter/jupyter_client/pull/852/files#diff-f89a7d6e5a8a1910d98e3a31ae8ff90c4d745d16bcef4a11d969e5459dcb7e50R810) in `Session` to be the culprit.

**Comment by bnavigator** [comment]
For the record, an update to jupyter_client 7.4.3 does not change anything here:

```
[   16s] + pytest-3.9 --ignore=_build. --ignore=_build.python39 --ignore=_build.python310 -v tests -k 'not (test_kernel_death or test_request_with_query)' --setup-show
[   16s] ============================= test session starts ==============================
[   16s] platform linux -- Python 3.9.14, pytest-7.1.2, pluggy-1.0.0 -- /usr/bin/python3.9
[   16s] cachedir: .pytest_cache
[   16s] rootdir: /home/abuild/rpmbuild/BUILD/voila-0.4.0rc0
[   16s] plugins: anyio-3.5.0, rerunfailures-10.2, tornasync-0.6.0.post2
[   17s] collecting ... collected 73 items / 6 deselected / 67 selected
[   17s] 
[   17s] tests/execute_output_test.py::test_execute_output 
[   17s]         SETUP    F sleep_between_tests
(...hangs indefinitely)
```

**Comment by bnavigator** [comment]
So skipping test_execute_output lets the rest of the test suite pass.

I stepped through the test and it hangs somewhere here:

```python
abuild@skylab:~/rpmbuild/BUILD/voila-0.4.0rc0> pytest --trace tests/execute_output_test.py 
===================================================== test session starts =====================================================
platform linux -- Python 3.10.7, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/abuild/rpmbuild/BUILD/voila-0.4.0rc0
plugins: anyio-3.5.0, rerunfailures-10.2, tornasync-0.6.0.post2
collected 1 item                                                                                                              

tests/execute_output_test.py 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB runcall (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/abuild/rpmbuild/BUILD/voila-0.4.0rc0/tests/execute_output_test.py(39)test_execute_output()
-> path = os.path.join(BASE_DIR, 'notebooks/output.ipynb')
(Pdb) n
> /home/abuild/rpmbuild/BUILD/voila-0.4.0rc0/tests/execute_output_test.py(40)test_execute_output()
-> nb = read(path, NO_CONVERT)
(Pdb) n
> /home/abuild/rpmbuild/BUILD/voila-0.4.0rc0/tests/execute_output_test.py(41)test_execute_output()
-> nb_voila = deepcopy(nb)
(Pdb) n
> /home/abuild/rpmbuild/BUILD/voila-0.4.0rc0/tests/execute_output_test.py(42)test_execute_output()
-> executenb(nb_voila)
(Pdb) s
--Call--
> /usr/lib/python3.10/site-packages/voila/execute.py(130)executenb()
-> def executenb(nb, cwd=None, km=None, **kwargs):
(Pdb) n
> /usr/lib/python3.10/site-packages/voila/execute.py(131)executenb()
-> resources = {}
(Pdb) n
> /usr/lib/python3.10/site-packages/voila/execute.py(132)executenb()
-> if cwd is not None:
(Pdb) n
> /usr/lib/python3.10/site-packages/voila/execute.py(135)executenb()
-> nb, resources = ClearOutputPreprocessor().preprocess(nb, resources)
(Pdb) n
> /usr/lib/python3.10/site-packages/voila/execute.py(136)executenb()
-> executor = VoilaExecutor(nb, km=km, **kwargs)
(Pdb) n
> /usr/lib/python3.10/site-packages/voila/execute.py(137)executenb()
-> return executor.execute(nb, resources, km=km)
(Pdb) s
--Call--
> /usr/lib/python3.10/site-packages/voila/execute.py(54)execute()
-> def execute(self, nb, resources, km=None):
(Pdb) n
> /usr/lib/python3.10/site-packages/voila/execute.py(55)execute()
-> try:
(Pdb) n
> /usr/lib/python3.10/site-packages/voila/execute.py(56)execute()
-> result = super(VoilaExecutor, self).execute()
(Pdb) s
--Call--
> /usr/lib/python3.10/site-packages/nbclient/util.py(84)wrapped()
-> def wrapped(*args, **kwargs):
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(85)wrapped()
-> return just_run(coro(*args, **kwargs))
(Pdb) s
--Call--
> /usr/lib/python3.10/site-packages/nbclient/util.py(40)just_run()
-> def just_run(coro: Awaitable) -> Any:
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(42)just_run()
-> try:
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(43)just_run()
-> loop = asyncio.get_running_loop()
(Pdb) n
RuntimeError: no running event loop
> /usr/lib/python3.10/site-packages/nbclient/util.py(43)just_run()
-> loop = asyncio.get_running_loop()
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(44)just_run()
-> except RuntimeError:
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(45)just_run()
-> loop = None
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(46)just_run()
-> if loop is None:
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(47)just_run()
-> had_running_loop = False
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(48)just_run()
-> loop = asyncio.new_event_loop()
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(49)just_run()
-> asyncio.set_event_loop(loop)
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(52)just_run()
-> if had_running_loop:
(Pdb) n
> /usr/lib/python3.10/site-packages/nbclient/util.py(60)just_run()
-> return loop.run_until_complete(coro)
(Pdb) n
### hang ###
```

**Comment by martinRenou** [comment]
Thanks a lot everyone for investigating! It looks like `jupyter_client 7.4.2` was indeed the culprit, we will have [an upper-bound for now](https://github.com/voila-dashboards/voila/pull/1239) and release 0.4.0.

**Comment by jtpio** [comment]
> It looks like `jupyter_client 7.4.2` was indeed the culprit

Does any of the `7.4.3` or `7.4.4` releases fix it?

**Comment by bnavigator** [comment]
No

**Comment by bnavigator** [comment]
Still an issue with jupyter_client 7.4.8

**Pull request merged**
