### PR TITLE
Add docs for deploying to Binder

### LINKED ISSUE #359: Document deploying to Binder
In the docs we should add a section for deploying voila on Binder.

A short paragraph with a link to https://mybinder.readthedocs.io/en/latest/introduction.html#preparing-a-repository-for-binder could be good enough to start with.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #359.

cc @maartenbreddels @martinRenou

### CODE REVIEW

**Comment by Alexboiboi** [comment]
Hi, there
I don't know if it is the right place to ask this but I was wondering if there is a way to give the dark theme when deploying to mybinder?

`?urlpath=voila/render/mynotebook.ipynb`  renders the notebook but how to assign options to it?


Also, is it possible to launch voila from a python script execution? (side question)

**Comment by jtpio** [comment]
@Alexboiboi the theme can be specified by creating a `jupyter_config.json` file with the following content:

```json
{
    "VoilaConfiguration": {
        "theme": "dark"
    }
}
```

Other options can be specified as well. There is an example in the [voila-demo](https://github.com/maartenbreddels/voila-demo) repo if you want to check it out.

I think it would make sense to add that to the "Deploy to Binder" docs (or point to the `voila-demo` repo as reference).

> Also, is it possible to launch voila from a python script execution? (side question)

To use on mybinder? Otherwise yes it's possible to do something like this:

```python
from voila.app import Voila
v = Voila()
v.initialize(['.', '--no-browser'])
v.start()
```

**Comment by Alexboiboi** [comment]
@jtpio Thanks a lot for your precise answer, this was very helpful!

**Comment by jtpio** [comment]
Added a section about the `jupyter_config.json` file.

**Comment by jtpio** [comment]
This one is ready to go.

**Comment by martinRenou** [comment]
Ok for me!

**Comment by jtpio** [comment]
Cool, let's get that in then.

**Pull request merged**
