### PR TITLE
Update the preview extension to JupyterLab 3.0

### PR DESCRIPTION
**Pull request by jtpio**
Update the preview extension so it is compatible with JupyterLab 3.0.

Note: this only updates the compatibility range, and does not use the new extension system and packaging (yet).

### CODE REVIEW

**Comment by jtpio** [comment]
This should now be compatible with the latest rc:

lab-3-rc2

**Comment by SylvainCorlay** [comment]
Feel free to go ahead and merge when you think this is ready.

**Comment by jtpio** [comment]
Looks like the tests are now failing, similar to https://github.com/voila-dashboards/voila-gridstack/issues/70

**Comment by jtpio** [comment]
Keeping a pin on `jupyter_server` for now for the tests. To be fixed in #785.

Follow-up PR will be to use the new distribution system for the preview extension: https://github.com/voila-dashboards/voila/issues/761

**Pull request merged**
