### PR TITLE
default to the base package to let the CDN handle browser/main resolution

### LINKED ISSUE #1128: Voila looks in the wrong location for an extension via CDN
# Description
Packages pushed to CDN may define widget/extension entrypoints other than `index.js`. 

xref: https://github.com/finos/perspective/issues/1773
voila extension loader: https://github.com/voila-dashboards/voila/blob/857eb692b1edd98ee59002fa39416df0d628f411/packages/voila/src/loader.ts#L44

# Expectation
We should inspect the [main attribute of the package.json](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#main) if possible to identify the entrypoint. 

# Context
voila version: all to date

### PR DESCRIPTION
**Pull request by timkpaine**
## References

Fixes #1128 
Fixes: https://github.com/finos/perspective/issues/1773

## Code changes
First try the base package path. The CDN should be smart enough to resolve this to the `browser` or `main` fields of the packages `package.json`, e.g. from unpkg docs:

Screen Shot 2022-05-07 at 11 47 06 PM

jsdelivr does the same thing as here

If this fails, we default to the existing behavior.

## User-facing changes

Should have greater extension compatibility.

## Backwards-incompatible changes

Should be none

### CODE REVIEW

**Comment by timkpaine** [comment]
Screen Shot 2022-05-08 at 12 18 44 AM

**Comment by trungleduc** [comment]
Hi @timkpaine, `Perspective` is a Jupyter Notebook extension or a JupyterLab extension?

**Comment by timkpaine** [comment]
@trungleduc lab, but it doesn't matter really. theres nothing special about `dist/index.js`, the `package.json` should specify where to look so hardcoding `dist/index.js` is not the correct behavior.

**Comment by maxrausch** [comment]
Any updates here?

**Comment by trungleduc** [comment]
Closing this PR since the changes are not applicable anymore with the next release of Voila.

**Pull request closed without merging**
