### PR TITLE
add iframe sandbox attribute to allow download of files

### PR DESCRIPTION
**Pull request by jamesjnadeau**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Hi James,

thanks, this PR looks good, I'm not sure why it fails. @jtpio can you take a look at this?

cheers,

Maarten

**Comment by jtpio** [comment]
> I'm not sure why it fails

It's a compile time failure because `allow-downloads` is not part of the list of exceptions specified here:

https://github.com/jupyterlab/jupyterlab/blob/c5e2e1af9bd96d65d055482848ddfd2a74bc5092/packages/apputils/src/iframe.ts#L106-L118

**Comment by jamesjnadeau** [comment]
not sure how to address that build failure reason, but this is blocking me from using some widget functionality when testing voila in jupyter lab. Adding the tag manually before doing a download seems to work around this.

here's the chrome status:
https://www.chromestatus.com/feature/5706745674465280

**Comment by jtpio** [comment]
> not sure how to address that build failure reason

The TypeScript build fails because `allow-downloads` is not allowed in the `SandboxExceptions` type here:

https://github.com/jupyterlab/jupyterlab/blob/c5e2e1af9bd96d65d055482848ddfd2a74bc5092/packages/apputils/src/iframe.ts#L106-L118

Would you like to open an issue in https://github.com/jupyterlab/jupyterlab to propose adding it?

**Comment by jamesjnadeau** [comment]
Thanks for the reminder on this @jtpio :)

I created a pull request to add an exception:
https://github.com/jupyterlab/jupyterlab/pull/9497

**Comment by jtpio** [comment]
Thanks @jamesjnadeau.

Since https://github.com/jupyterlab/jupyterlab/pull/9497 has been merged, would you like to rebase this PR onto the latest master?

**Comment by jamesjnadeau** [comment]
@jtpio I just rebased to the latest master, 🤞 the CI completes.

**Comment by jamesjnadeau** [comment]
@jtpio all set, see you add prettier :) nice

**Comment by jtpio** [comment]
Thanks @jamesjnadeau.

It looks like the GitHub diff shows a lot of changes, so maybe something went wront during the rebase?

image

Would it be possible to recreate the single original commit with the change? It would also be fine to recreate a PR otherwise.

**Comment by jamesjnadeau** [comment]
so this seems like a mess now for just a single line change, i'm going to remake this pr and push another clened up one. I'll link to it here.

**Pull request closed without merging**
