### PR TITLE
Update @jupyterlab/services dependency to version 6.1.8

### PR DESCRIPTION
**Pull request by julian-west**
## References

Addresses #929 

Bumping up @jupyterlab/services dependency to version 6.1.8 includes the rendering delay fix already implemented for Jupyterlab (jupyterlab/jupyterlab#10321). This significantly reduces the delay before widgets are rendered in the browser.

## Code changes

Updated dependency specified in `voila/packages/voila/packages.json`

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @julian-west!

> Bumping up @jupyterlab/services dependency to version 6.1.8

This probably means we should also update the `yarn.lock` file: https://github.com/voila-dashboards/voila/blob/master/yarn.lock

Have you tried running `jlpm` locally, followed by `jlpm run build` to rebuild the frontend? There are some development instructions in the contributing guide: https://voila.readthedocs.io/en/latest/contribute.html

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by julian-west** [comment]
Thanks @jtpio! Do you know when you will be releasing the version 0.2.11? 

Would you be able to release an alpha version (e.g. 0.2.11a0) that includes this dependency update which we can use in the meantime?

**Comment by jtpio** [comment]
@julian-west I'm planning to cut 0.2.11 soon (today or tomorrow) to include this fix as well as other recent fixes.

**Comment by jtpio** [comment]
@julian-west `0.2.11` is out: https://github.com/voila-dashboards/voila/releases/tag/0.2.11

**Comment by julian-west** [comment]
Thank you! :)

**Pull request merged**
