### PR TITLE
Update publish workflow for trusted publishers

### PR DESCRIPTION
**Pull request by jtpio**
## References

Start using trusted publishers for publishing Voila to PyPI.

This will help to not have to deal with 2FA with the bot account: https://blog.pypi.org/posts/2024-01-01-2fa-enforced/

## Code changes

- [x] Update `publish-release.yml` to remove the PyPI token and set up `id-token`
- [x] Setup `voila` on PyPI to use trusted publishers

image

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
We can then remove `voila-bot` from PyPI after this is merged.

**Comment by jtpio** [comment]
> We can then remove `voila-bot` from PyPI after this is merged.

And the `PYPI_TOKEN` in the repo secrets.

Looks like `voila-bot` was only used for 2 projects on PyPI:

image

**Comment by martinRenou** [comment]
Happy to remove that bot, thank you!

**Comment by jtpio** [comment]
Just removed it from PyPI. I think we need to keep as `Admin` on the repos though.

**Comment by martinRenou** [comment]
> I think we need to keep as Admin on the repos though.

Why?

**Comment by jtpio** [comment]
Because it's still the bot creating the GitHub releases:

image

There is also still the need to the admin github token. But this might not be needed in a future version of the releaser: https://github.com/jupyter-server/jupyter_releaser/pull/545

**Comment by martinRenou** [comment]
Ok 👍🏽

**Pull request merged**
