### PR TITLE
Render Javascript output

### PR DESCRIPTION
**Pull request by trungleduc**
## References
https://github.com/voila-dashboards/voila/issues/743

## Code changes

Replace the javascript render factory from ` @jupyterlab/rendermime` with one from `@jupyterlab/javascript-extension`

## User-facing changes

javascript output now works in voila as in jupyterlab

voila

## Backwards-incompatible changes
N/A

### CODE REVIEW

**Comment by jtpio** [comment]
> so it's time to update reference screenshot?

I think so yes.

**Comment by jtpio** [comment]
Just rebased onto the latest to pick up the change from https://github.com/voila-dashboards/voila/pull/934

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by gunstonej** [comment]
this is great - thanks @trungleduc  and @jtpio !

I just tested on my machine  -

it is working for me when Voila is rendered in `http://localhost:8866/` 👍 

... but when rendering using the Jupyter Lab voila renderer i get the following error: 

> `VM666:1 Blocked opening 'https://jupyter.org/' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.`

image

any ideas? 

cheers

**Comment by jtpio** [comment]
It's probably because the preview does not allow the popups here:

https://github.com/voila-dashboards/voila/blob/9fa04ce10e2a5f76bb2d272a67cb79698ac138ba/packages/jupyterlab-preview/src/preview.tsx#L50

We could add that sandbox property to the list.

**Pull request merged**
