### PR TITLE
Fix ipywidgets 7.7 incompatibility issue

### PR DESCRIPTION
**Pull request by martinRenou**
## References

Fix https://github.com/voila-dashboards/voila/issues/1119

## Code changes

This removes all the widgets fetching logic from Voila and relies on ipywidgets for doing it.

## User-facing changes

Voila and ipywidgets 7.7 should now be compatible, fixing some issues when widgets have child widgets.

Note that the Front-end code now builds against the 7.7 widget manager, but this should not have an impact on ipywidgets <7.7 compatibility (tested locally with 7.6)

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Cool, so `_loadFromKernel` is a new API from the widget manager, then I should check if https://github.com/voila-dashboards/voila/pull/1101 is present in that.

**Comment by trungleduc** [comment]
Thanks @martinRenou, we need to update some screenshots for the UI test.  I do not recall the command for the bot.

**Comment by martinRenou** [comment]
> then I should check if https://github.com/voila-dashboards/voila/pull/1101 is present in that.

I guess not, maybe we should upstream that PR to ipywidgets

> we need to update some screenshots for the UI test. I do not recall the command for the bot.

Please update galata references

**Comment by maartenbreddels** [comment]
> I guess not, maybe we should upstream that PR to ipywidgets
> 
> >

yeah, that's what I meant to say

**Comment by trungleduc** [comment]
Restart CI

**Review by trungleduc — APPROVED** [review]

**Comment by trungleduc** [comment]
Thanks @martinRenou!

**Pull request merged**
