### PR TITLE
Add UI Tests

### LINKED ISSUE #915: End to End testing
### Problem

Visual regressions can sometimes be introduced when making changes to Voila.

For example #846 is going to drastically change the way the frontend works, and it would be great to check if this big change is going to affect some of the Voila logic, rendering or features.

### Proposed Solution

We should add Visual Regression tests, which has already been explored in https://github.com/voila-dashboards/voila/pull/574 and https://github.com/voila-dashboards/voila/pull/821.

One option would be to follow what JupyterLab, ipywidgets and bqplot (and potentially other repos) have done and adop Galata: https://github.com/jupyterlab/galata

If testing the Voila rendered page directly is not feasible with Galata, we might able to use the JupyterLab preview extension instead.

### Additional context

- https://github.com/voila-dashboards/voila/pull/574 
- https://github.com/voila-dashboards/voila/pull/821
- https://github.com/jupyterlab/jupyterlab/tree/master/ui-tests
- https://github.com/jupyter-widgets/ipywidgets/tree/master/ui-tests

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #915 
Closes #574 
Closes #821 

Add UI tests using Galata

### TODO

- [x] Boostrap the UI tests similar to jupyterlab and ipywidgets
- [x] Open the JupyterLab preview
- [x] Add CI workflow
- [x] Add reference screenshots
- [x] Wait for notebook run in the IFrame

## Code changes

Add UI tests code

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

**Comment by jtpio** [comment]
Ah we might need to also wait for MathJax to finish rendering the elements:

voila_basics

**Comment by jtpio** [comment]
cc @martinRenou if you want to check it out.

For now it doesn't test much, just the `basics.ipynb` notebook with a reference screenshot. But the base structure should now be in place to easily add new test cases later on.

**Comment by martinRenou** [comment]
Looks good!!

Sorry I missed the ping here.

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
