### PR TITLE
Fix default VOILA_WS_BASE_URL value in preheating mode

### LINKED ISSUE #1140: Kernels don't get the query string if `--Voila.base_url` is specified and preheating is turned on
## Description

Hi!
When I was updating Voila from 0.3.1 to 0.3.5 on my machine, I saw that the preheated kernels produced some warning messages even before leaving the kernels pool. After taking a look at the recent changes, I found out that specifying the `VOILA_WS_BASE_URL` env. variable was now required to use the `--Voila.base_url` parameter.

## Reproduce

1. Create a `get_qs_example.ipynb` file with the following code:
```
from voila.utils import get_query_string
print(get_query_string())
```
2. Run the Voila server as follows:
```
voila get_qs_example.ipynb --preheat_kernel=True --pool_size=5 --no-browser --Voila.base_url='/example-base-url/'
```
3. See the following warnings in the Voila logs:
```
[Voila] Using /var/folders/44/nmhwstjd0cvg9yzpq0463l600000gn/T to store connection files
[Voila] Storing connection files in /var/folders/44/nmhwstjd0cvg9yzpq0463l600000gn/T/voila_54cdmtsg.
[Voila] Serving static files from /Users/vadym_kaidalov/opt/miniconda3/envs/playground/lib/python3.10/site-packages/voila/static.
[Voila] Voilà is running at:
http://localhost:8866/example-base-url/
[Voila] WARNING | Notebook get_qs_example.ipynb is not trusted
[Voila] WARNING | Notebook get_qs_example.ipynb is not trusted
[Voila] WARNING | Notebook get_qs_example.ipynb is not trusted
[Voila] WARNING | Notebook get_qs_example.ipynb is not trusted
[Voila] WARNING | Notebook get_qs_example.ipynb is not trusted
[Voila] Kernel started: 5a1dc72b-acac-4fe1-961b-b0d023c5c588
[Voila] Kernel started: fe5a586b-c425-4397-a5a7-240e21865d74
[Voila] Kernel started: 7801ca4b-214c-49b5-bf40-774ae1c0c457
[Voila] Kernel started: 04a9568f-b42c-46e0-a242-7addefb6a067
[Voila] Kernel started: e22cdcc1-547e-4e52-9ca7-b8de8d199d45
[Voila] Kernel pool of get_qs_example.ipynb is filled with 5 kernel(s)
WARNING:tornado.access:404 GET /voila/query/04a9568f-b42c-46e0-a242-7addefb6a067 (127.0.0.1) 1.77ms
WARNING:tornado.access:404 GET /voila/query/fe5a586b-c425-4397-a5a7-240e21865d74 (127.0.0.1) 0.41ms
WARNING:tornado.access:404 GET /voila/query/7801ca4b-214c-49b5-bf40-774ae1c0c457 (127.0.0.1) 0.39ms
WARNING:tornado.access:404 GET /voila/query/e22cdcc1-547e-4e52-9ca7-b8de8d199d45 (127.0.0.1) 2.39ms
WARNING:tornado.access:404 GET /voila/query/5a1dc72b-acac-4fe1-961b-b0d023c5c588 (127.0.0.1) 1.62ms
```
According to the source code, the VoilaHandler ignores the WebSocket connection error and goes on with an empty query string value.
4. Go to http://localhost:8866/example-base-url/?foo1=bar1&foo2=bar2 in the browser and see `None` instead of the expected `foo1=bar1&foo2=bar2` value.

## Expected behavior

I managed to modify my bash script to make app work correctly by providing the `VOILA_WS_BASE_URL` env. var. as follows:
```
voila get_qs_example.ipynb --preheat_kernel=True --pool_size=5 --no-browser --Voila.base_url='/example-base-url/' --VoilaKernelManager.kernel_pools_config="{'get_qs_example.ipynb': {'pool_size': 5, 'kernel_env_variables': {'VOILA_WS_BASE_URL': '/example-base-url/'}}}"
```
However, it's still a breaking change as I had to modify my bash script and I would expect Voila to use the value of `--Voila.base_url` parameter if the `VOILA_WS_BASE_URL` variable hasn't been specified.

### PR DESCRIPTION
**Pull request by vkaidalov-rft**
## References

Resolves #1140.

## Code changes

Use `VOILA_BASE_URL` as the default value if `VOILA_WS_BASE_URL` has not been specified to make the `wait_for_request` and `get_query_string` functions backwards-compatible in the preheating mode.

### CODE REVIEW

**Comment by trungleduc** [comment]
Thanks @vkaidalov-rft for your PR! 
I want to add some tests for this fix to prevent any future breaking changes. Can i push directly these tests to your branch?

**Comment by vkaidalov-rft** [comment]
Hi @trungleduc, sure!
Is there anything I should do to let you push commits directly into my branch?

**Comment by vkaidalov-rft** [comment]
> Hi @trungleduc, sure! Is there anything I should do to let you push commits directly into my branch?

I can see I've "allowed edits by maintainers" for this PR, so I suppose nothing else is needed.

**Comment by trungleduc** [comment]
Thank! I will  ping you when I push my commits

**Comment by trungleduc** [comment]
@vkaidalov-rft I updated your fix since the default WebSocket handler is at `server_url` and not `base_url` (https://github.com/voila-dashboards/voila/blob/9afaaf07c9984e68f4e38f746c1c83413bc2818d/voila/app.py#L500-L502)

And `server_url` defaults to `base_url` if it is not set https://github.com/voila-dashboards/voila/blob/9afaaf07c9984e68f4e38f746c1c83413bc2818d/voila/app.py#L448

So it will work as expected.

**Comment by vkaidalov-rft** [comment]
Thank you, @trungleduc! I've checked your changes and can confirm everything still works as expected 👍

**Comment by trungleduc** [comment]
@martinRenou can you take a look at this PR as I contributed quite extensively on this one?

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
