### PR TITLE
Adopt monorepo structure

### PR DESCRIPTION
**Pull request by jtpio**
Adopt a monorepo structure with `lerna` to streamline the build process, and align the setup with current practices also used in other repos.

This makes it easier to build the packages with a single streamlined workflow:

```bash
jlpm
jlpm run build
```

This is in preparation for switching to TypeScript for the Voila frontend, and to the lab 3 based frontend later on.

### TODO

- [x] Strict null checks
- [x] Lint check on CI
- [x] Simplify `setup.py`
- [x] Update contributing guide
- [x] Lint `packages/voila`

### CODE REVIEW

**Comment by jtpio** [comment]
cc @martinRenou if you want to review, since you've also been looking at similar structures and build systems recently.

The idea would be to merge this PR first before migrating to TypeScript for the Voila frontend.

**Comment by jtpio** [comment]
Reverted back to the commit where CI was passing: 0108d27bb82ab177e4cd592197ecc822fea8a6e6:

image

Need to investigate why the Voila tests suddenly started to fail now.

**Comment by jtpio** [comment]
https://github.com/voila-dashboards/voila/pull/808/commits/e0be580af62c631115e6762f3cf5a320e5d48c99 should fix #755

**Comment by jtpio** [comment]
Recreating an environment from scratch and rerunning the tests locally with `python -m pytest` seems to work fine:

image

However, running with `VOILA_TEST_DEBUG=1 VOILA_TEST_XEUS_CLING=1 python -m pytest` yields similar errors as on CI:

image

**Comment by jtpio** [comment]
Looks like this has to do with the recent `0.6.24` release of `xtl` published yesterday:

image

As downgrading to `0.6.23` seems to fix it:

https://user-images.githubusercontent.com/591645/105355507-8ebe9500-5bf2-11eb-8755-80fc4b2de6d2.mp4

**Comment by jtpio** [comment]
Tests are green again with the pin to `xtl=0.6.23` in 1372b45b1d628491cdd15446f193d3b6fac75b5c

**Comment by JohanMabille** [comment]
I think it's fine to pin to `xtl=0.6.23` for now. The xeus-cling stack must be rebuilt so it uses the same standard lib as the last `xtl`

**Comment by jtpio** [comment]
> I think it's fine to pin to `xtl=0.6.23` for now. The xeus-cling stack must be rebuilt so it uses the same standard lib as the last `xtl`

OK sounds good, thanks for the heads-up :+1: 

We can open a new issue to remember to unpin at some point in the future.

**Comment by jtpio** [comment]
Thanks Martin and Johan!

Looks good now, so we can merge and iterate in follow-up PRs.

**Comment by jtpio** [comment]
Opened https://github.com/voila-dashboards/voila/issues/812 to keep track of the unpin.

**Pull request merged**
