### PR TITLE
Adds documentation about the template cookiecutter to CONTRIBUTING

### PR DESCRIPTION
**Pull request by AartGoossens**
I talked about this PR with @jtpio during the PyConDE 2019 sprints.

I created a Voila template cookiecutter to:
1. Help the creation of new Voila templates.
2. Make template development easier by offering some docker configuration that let's you live reload your changes.

The cookiecutter can be found [here](https://github.com/AartGoossens/voila/pull/new/feature/template-cookiecutter-docs).
If you are willing to merge this PR I would also like to propose to copy the cookiecutter repo to the `voila-dashboards` Github organization.

Cheers!

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @AartGoossens for this!

Docker is indeed a good alternative to iterate on templates locally.

I also think it makes sense to move the cookiecutter repo to the voila-dashboards organization, this will make it much more visible.

We probably still want to keep another way to work on templates locally, mostly for users who don't know what Docker is or don't want to use it. In this case adding the usual `pip install .` instructions should be enough (or to the `Makefile`).

**Comment by SylvainCorlay** [comment]
@AartGoossens thanks for this!

I have invited you to become a member of the voila-dashboards github organization!

As a byproduct, you should be able to transfer the cookiecutter to the organization.

**Comment by AartGoossens** [comment]
> We probably still want to keep another way to work on templates locally, mostly for users who don't know what Docker is or don't want to use it. In this case adding the usual pip install . instructions should be enough (or to the Makefile).

Do you propose to add these `pip install .` instructions here (i.e. in to core repo) or in the cookiecutter repo?

And how do you want to handle moving the cookiecutter repo to the voia-dashboards organization?

**Comment by AartGoossens** [comment]
I moved the cookiecutter repo to this github org: https://github.com/voila-dashboards/voila-template-cookiecutter
...and changed the url accordingly in CONTRIBUTING.md.

**Comment by SylvainCorlay** [comment]
Thanks @AartGoossens!

**Comment by SylvainCorlay** [comment]
By the way, @AartGoossens you can make your membership to the organization public if you want the voila badge in your public profile. Cheers.

**Comment by jtpio** [comment]
Thanks for transferring the repo.

It would be great to mention the cookiecutter in this section of the docs too: https://voila.readthedocs.io/en/latest/customize.html#creating-your-own-template

**Comment by AartGoossens** [comment]
@jtpio done :heavy_check_mark:

**Comment by jtpio** [comment]
Thanks again @AartGoossens!

**Pull request merged**
