### PR TITLE
feat: use asyncio to execute cells

### PR DESCRIPTION
**Pull request by maartenbreddels**
This allows concurrent requests, instead of blocking requests when cells are executed

### CODE REVIEW

**Comment by jtpio** [comment]
This already looks much nice with `async / await`.

Note: this drops support for Python 2 :tada:

**Comment by maartenbreddels** [comment]
Yes, I should change .travis.yml. But how do we test py35? conda-forge doesn't do that anymore right? We'd have to test that using pip?

**Comment by maartenbreddels** [comment]
This PR is needed for the asyncio jupyter client: https://github.com/jupyter/jupyter_client/pull/471

And there are issues with connecting to the kernel, and widgets do not seem to work.

**Comment by SylvainCorlay** [comment]
Closing as superseeded by several PRs by @maartenbreddels and @davidbrochart.

**Pull request closed without merging**
