### PR TITLE
Simplify actions

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Now that we can drop 3.5, rebasing should get the tests to pass.

@martinRenou

**Comment by jtpio** [comment]
Linking to the conversation on gitter: https://gitter.im/QuantStack/Lobby?at=5ee247be36589658b12b9026

We might want to try with `setup-miniconda` action, and even enable `mamba`.

It might even help fixing #526 too.

**Comment by jtpio** [comment]
wow thanks @martinRenou for the update. Let's see how it goes!

**Comment by martinRenou** [comment]
I'll enable Windows too, see what happens

**Comment by jtpio** [comment]
Windows used to be an issue because of xeus-cling (but there could be a condition to handle that)

**Comment by martinRenou** [comment]
Looks like `python` refers to the `/usr/bin` one, not the conda installed one.

**Comment by jtpio** [comment]
The other jobs (ubuntu and macos) are passing, nice :+1: 

We could also fix windows separately.

**Comment by martinRenou** [comment]
Yeah although there is still one failing on Macos. I'll look at it later.

**Comment by martinRenou** [comment]
I rerun the test and it's now passing. There might be a race condition in the tests.

Let's disable Windows tests for now then.

**Comment by martinRenou** [comment]
@jtpio All green. Ok to merge?

**Comment by jtpio** [comment]
That looks good and much simpler, thanks a lot!

Happy to go for it if we're fine using mamba on CI.

**Pull request merged**
