### PR TITLE
Move js/ (voila standalone frontend) to packages/

### PR DESCRIPTION
**Pull request by jtpio**
Move the `js` folder to `packages`, so both the standalone frontend and the JupyterLab extension sit next to each other.

A follow-up for this change would be to slightly rework `setup.py` to also run `npm pack` for the JupyterLab extension and install it automatically as `data_file`.

### CODE REVIEW

**Comment by jtpio** [comment]
Test failure looks relevant.

`tests/app/image_inlining_test.py` passes locally when executed alone (`python -m pytest -k "test_image_inlining"`)

But it doesn't pass when started with `python -m pytest` and running after `tests/app/execute_test.py` (which errors with `..Task was destroyed but it is pending`)

**Comment by maartenbreddels** [comment]
It also seems to be failing in master, so might be an external dependency, jupyter_client is what @SylvainCorlay suggested, but the inlining might be nbconvert?

**Comment by SylvainCorlay** [comment]
There was an nbconvert release?

**Comment by maartenbreddels** [comment]
Not that i know of or checked, but I doubt the inlining error has something to do with jupyter_client, although not impossible.

**Comment by jtpio** [comment]
Rebased to check if the tests would pass.

**Comment by maartenbreddels** [comment]
should we directly move it to the proper name? `packages/voila`?

**Comment by jtpio** [comment]
`packages/voila` sounds like a better name indeed.

**Comment by jtpio** [comment]
Closing in favor of #786.

**Pull request closed without merging**
