### PR TITLE
Add docs for running voila on a private server

### PR DESCRIPTION
**Pull request by jtpio**
Add documentation to deploy voila on a private server behind nginx, as a follow-up for the [question asked on gitter](https://gitter.im/QuantStack/Lobby?at=5d5bcd6f7d56bc60808d5f00).

### CODE REVIEW

**Comment by jtpio** [comment]
cc @berceanu: feedback welcome

Feel free to comment here or open a PR against my branch if you would like to add more details or make suggestions.

**Comment by jtpio** [comment]
We can also consider adding a section to enable HTTPS with Let's Encrypt, for example by pointing to an existing guide: https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/

**Comment by berceanu** [comment]
I see you use a global install via pip. The way I set it up is to use a conda env inside the user's home's dir. That requires changing the service file a bit - would you like me to update?

**Comment by jtpio** [comment]
Yes this assumes the instance is only running voila (global).

Maybe the conda env setup can be added as an alternative to having things installed globally?

**Comment by berceanu** [comment]
Well, I was imagining a typical usage scenario might be: you have a repo, with an `evironment.yml` file, you hack on it as a normal usage in a conda env, but then want to easily serve the notebooks via voila.

**Comment by jtpio** [comment]
For this scenario, using Binder (and more precisely [mybinder.org](https://mybinder.org)) would probably be easier (if the repo is public).

For a private instance, another way would be to [deploy a voila gallery](https://github.com/voila-gallery/gallery#deploying-your-own-gallery).

**Comment by berceanu** [comment]
I wasn't aware you can use voila on mybinder.

**Comment by jtpio** [comment]
We should add that (deploying on Binder) to the docs too.

**Comment by jtpio** [comment]
Opened https://github.com/QuantStack/voila/issues/359

**Comment by jtpio** [comment]
@maartenbreddels maybe you want to try it out? (iirc you deployed voila to a bare EC2 instance for a demo once)

Otherwise this is ready to go.

**Comment by jtpio** [comment]
This PR was just rebased onto the latest master.

Since it has been open for a long time and there is no objection against it, we can go ahead and merge it.

Happy to iterate on it later on if needed.

**Comment by numice** [comment]
I notice the newly added private server section in the source but somehow it's still not in the docs.

**Comment by jtpio** [comment]
@numice the new section should show up using the "latest" badge: https://voila.readthedocs.io/en/latest/deploy.html#running-voila-on-a-private-server

image

**Comment by numice** [comment]
@jtpio Aha. I see it now. Thanks for the reply

**Pull request merged**
