### PR TITLE
Update environment.yml

### PR DESCRIPTION
**Pull request by astrojuanlu**
Fix https://github.com/voila-dashboards/voila/issues/898

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by astrojuanlu** [comment]
`test_execute_output` failed on macOS-latest with Python 3.8, do you think it's related to this PR?

**Comment by jtpio** [comment]
It shouldn't be related, just restarted the CI to see.

**Comment by jtpio** [comment]
All green, thanks!

**Pull request merged**
