### PR TITLE
Add tests for Python 3.11

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks!

Let's add the 3.11 classifier as well?

https://github.com/voila-dashboards/voila/blob/20caacc4d1a5749fd94b709f84b73c452367f589/pyproject.toml#L34

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Kicking CI to see if the windows 3.11 check is relevant.

**Comment by jtpio** [comment]
The windows 3.11 checks still seems to be failing after the kick: https://github.com/voila-dashboards/voila/actions/runs/3460990908/jobs/5778083081

**Comment by trungleduc** [comment]
the failed test on `windows` with python 3.11 does seem legit.

**Comment by martinRenou** [comment]
Are you able to reproduce it?

**Comment by trungleduc** [comment]
this test failed also in `ubuntu` https://github.com/voila-dashboards/voila/actions/runs/4481338678/jobs/7877899131?pr=1240

**Comment by martinRenou** [comment]
Funny enough, the windows tests are not passing, but the CI is green

```
platform win32 -- Python 3.10.11, pytest-7.4.0, pluggy-1.2.0
rootdir: D:\a\voila\voila
plugins: anyio-3.7.1, cov-4.1.0, rerunfailures-12.0, tornasync-0.6.0.post2
collected 55 items

tests\app\config_paths_test.py ....                                      [  7%]
tests\app\cwd_subdir_test.py .                                           [  9%]
tests\app\cwd_test.py .                                                  [ 10%]
tests\app\execute_cpp_test.py s                                          [ 12%]
tests\app\execute_test.py ..                                             [ [16](https://github.com/voila-dashboards/voila/actions/runs/5728538292/job/15523330698?pr=1240#step:6:17)%]
tests\app\image_inlining_test.py .                                       [ [18](https://github.com/voila-dashboards/voila/actions/runs/5728538292/job/15523330698?pr=1240#step:6:19)%]
tests\app\kernel_death_test.py R.                                        [ [20](https://github.com/voila-dashboards/voila/actions/runs/5728538292/job/15523330698?pr=1240#step:6:21)%]
tests\app\many_iopub_messages_test.py .                                  [ [21](https://github.com/voila-dashboards/voila/actions/runs/5728538292/job/15523330698?pr=1240#step:6:22)%]
tests\app\nbextensions_test.py s                                         [ [23](https://github.com/voila-dashboards/voila/actions/runs/5728538292/job/15523330698?pr=1240#step:6:24)%]
tests\app\no_kernelspec_test.py .                                        [ [25](https://github.com/voila-dashboards/voila/actions/runs/5728538292/job/15523330698?pr=1240#step:6:26)%]
tests\app\no_strip_sources_test.py .                                     [ [27](https://github.com/voila-dashboards/voila/actions/runs/5728538292/job/15523330698?pr=1240#step:6:28)%]
tests\app\non_existing_kernel_test.py .                                  [ [29](https://github.com/voila-dashboards/voila/actions/runs/5728538292/job/15523330698?pr=1240#step:6:30)%]
tests\app\notebooks_test.py .                                            [ [30](https://github.com/voila-dashboards/voila/actions/runs/5728538292/job/15523330698?pr=1240#step:6:31)%]
tests\app\preheat_activation_test.py .RRF.RRFRRFRRF                      [ 41%]
tests\app\preheat_configuration_test.py RRFRRF                           [ 45%]
tests\app\preheat_default_kernel_env_test.py RRF                         [ 47%]
tests\app\preheat_multiple_notebooks_test.py RRF.                        [ 50%]
tests\app\preheat_with_query_string_test.py ....                         [ 58%]
tests\app\prelaunch_hook_papermill_test.py .                             [ 60%]
tests\app\prelaunch_hook_test.py .                                       [ 61%]
tests\app\preprocessor_test.py .                                         [ 63%]
tests\app\serve_directory_test.py ..s                                    [ 69%]
tests\app\show_traceback_test.py ..                                      [ 72%]
tests\app\shutdown_kernel_test.py .                                      [ 74%]
tests\app\static_files_test.py .....                                     [ 83%]
tests\app\syntax_error_test.py .                                         [ 85%]
tests\app\template_arg_test.py .                                         [ 87%]
tests\app\template_cli_test.py .                                         [ 89%]
tests\app\template_config_file_test.py .                                 [ 90%]
tests\app\template_custom_test.py .                                      [ 92%]
tests\app\template_sanity_test.py ..                                     [ 96%]
tests\app\timeout_test.py .                                              [ 98%]
tests\app\tree_test.py .                                                 [100%]
```

**Comment by trungleduc** [comment]
Maybe the preheated mode is not activated correctly?

**Comment by martinRenou** [comment]
I'll dig deeper tomorrow morning

**Pull request merged**
