### PR TITLE
Fix timeout=None

### PR DESCRIPTION
**Pull request by davidbrochart**
See https://github.com/voila-dashboards/voila/issues/587#issuecomment-622457068

### CODE REVIEW

**Comment by maartenbreddels** [comment]
#541 will remove this again right?

**Comment by davidbrochart** [comment]
I can make it part of #541.

**Comment by maartenbreddels** [comment]
Whatever you think is more natural, i'm not sure where it should go actually after that PR is merged, since that code/method is removed.

**Comment by davidbrochart** [comment]
Ah you're right, it should be in nbclient now but it's already fixed there. Closing!

**Pull request closed without merging**
