### PR TITLE
WIP - Filter empty cells

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by vidartf** [comment]
As long as the filter does not remove any cell cells where the output is populated later (I'm not sure what cell.outputs is in that case), this is OK as well.

**Comment by maartenbreddels** [comment]
My preference goes to solving this in the template, and for instance not do this in the debug template.

**Comment by martinRenou** [comment]
Well, we actually still do that in the template. The only difference is that we don't add empty cells in the page, instead of only making them invisible.

**Comment by vidartf** [comment]
A way to get an empty output (but I guess this makes the cell be not empty, so this should still be ok):
```py
display({}, raw=True, display_id=True)
```

**Comment by martinRenou** [comment]
But:
```python
handle = display({}, raw=True, display_id=True)
handle.update({'text/html': 'test'})
```
does not seem to show anything (in classic Notebook)

**Comment by vidartf** [comment]
It works in lab though.

**Comment by martinRenou** [comment]
> It works in lab though.

And actually it works in Voila as well. Both using master and this branch.

**Comment by vidartf** [comment]
Yes, but the question is then: Does #391 work?

**Comment by martinRenou** [comment]
Yes, for the same reason. `cell.outputs` is not None in the template, so we don't hide it in CSS

**Comment by maartenbreddels** [comment]
As discussed, cells should always be returned, since voila has the option to show the source code. Also, filtering out cells is impossible, since we don't know a priori if a cell will not contain output, and to make the progress indicator work, we need to return as many cells as there are in the notebook.

I think that only leaves the option open for a template to have custom behavior for empty output cells, e.g. only have an if statement in the template:
```
{% if 'outputs' in cell and cell.outputs %>
```

**Comment by martinRenou** [comment]
Closing in favor of #391

**Pull request closed without merging**
